services:
  postgres:
      image: postgres:15-alpine
      container_name: denet_db
      environment:
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASSWORD}
        POSTGRES_DB: ${PG_DATABASE_NAME}
      volumes:
        - denet_data:/var/lib/postgresql/data
      ports:
      - "${PG_PORT}:5432" 
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 5
  migrator:
    build: .
    image: denet_migrator
    container_name: denet_migrator
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "./goose postgres \"postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE_NAME}?sslmode=disable\" -dir /app/migrations up || [ $? -eq 3 ]"]
    volumes:
      - ./migrations:/app/migrations

  app:
    build: .
    image: denet
    container_name: 'denet'
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      ENV_PATH: /app/.env 
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

volumes:
  denet_data:
